### ISSUE TITLE
[META] cleanup follow ups to #38

### ISSUE THREAD

**Issue by MHBauer** [kubernetes-incubator/service-catalog#150]
- [x] fix the build of apiserver to be more like everything else.
   - [x] make file
   - [x] docker
- [x] logging
- [x] in the main command, uncomment the installers of the apis, and modify them to point to our apis
- [x] check what `make apiserver` does and adjust the result
- [x] update version response in doc
   - [ ] add our info to the version response?
   - [x] re-run curl to show version api
- [ ] extra triple backquote in doc end
- [ ] check cobra version necessity
- [ ] explain/doc file locations (short answer is: convention)
- [x] group constants in server definition see 9b20194682ff2266e1fc26d55fefe26cbafd598d
- [x] cleanup extra commented out code.

**Comment by pmorie** [comment]
Moving this to MVP-1 for reassesment.

**Comment by simonleung8** [comment]
@pmorie 
Since @MHBauer is on vacation, I will help finishing up this issue

**Comment by simonleung8** [comment]
- cleanup extra commented out code is done with the #484 merge

**Comment by simonleung8** [comment]
I think the following 2 issues are resolved
>  extra triple backquote in doc end

I don't see any extra backquote

>  check cobra version necessity

It is good to define a version, so there won't be any unexpected incompatibility issue.
we are currently using the same version as k8s core

---

@pmorie 
For the rest of the issues, there is not enough context in the description for me to go on, so I will drop this work item at this point. Someone with more context could pick it up
> add our info to the version response?
> explain/doc file locations (short answer is: convention)

**Comment by pmorie** [comment]
If we don't know what else there is to fix, I'm calling this done.  Thanks for picking it up @simonleung8

**Comment by MHBauer** [comment]
definitely done. version response fails due to kubectl negotiation blowing up, so there isn't anything to see unless we write our own client.
