### ISSUE TITLE
[Meta] Remove the "old" controller

### ISSUE THREAD

**Issue by arschles** [kubernetes-incubator/service-catalog#482]
The "new" controller is in `./pkg/controller/wip`, and it will be fully functional after https://github.com/kubernetes-incubator/service-catalog/pull/403 is in. The old controller code should be removed and the `controller/wip` code should be moved under `./pkg/controller`.

Along with this change, any applicable documentation and the `./deploy/catalog` chart, which is outdated, should be updated.

List of TODOs mentioned above:

- [x] Remove the old controller code (#486)
- [x] Move the wip controller code into `./pkg/controller` (https://github.com/kubernetes-incubator/service-catalog/pull/495)
- [x] Remove the `./deploy/catalog` helm chart and rename the `./deploy/wip-catalog` chart to `./deploy/catalog` #503 
- [ ] Update any necessary docs

Requires #403

**Comment by pmorie** [comment]
I can take this one once #403 is merged.

**Comment by arschles** [comment]
reopening, since this is still in progress

**Comment by pmorie** [comment]
I think #503 should also cover your (4), @arschles - do you agree?

**Comment by arschles** [comment]
@pmorie yes

**Comment by pmorie** [comment]
This is done - closing
